### ISSUE TITLE
FileNotFoundException: Could not load file or assembly ...

### ISSUE THREAD

**Issue by orcunhanay** [aws/porting-assistant-dotnet-ui#786]
Hi,

I get the error "System.IO.FileNotFoundException: Could not load file or assembly" during the assessment, but Visual Studio's build is successful and the files exist in related folders. I check and see related files when starting a build by Visual Studio 2022, but there are no files in the folder when starting an assessment by Porting Assistant.

This solution file contains the Silverlight and Asp.Net Web Application projects. Is Porting Assistant for .Net support? 

Log;

[2023-03-14 15:41:07 ERR] (1.9.2) PortingAssistant.Client.Analysis.PortingAssistantAnalysisHandler: Error while resolving reference Microsoft.CodeAnalysis.MetadataImageReference System.IO.FileNotFoundException: Could not load file or assembly '...\bin\Debug\XYZ.dll'. The system cannot find the file specified. File name: '...\bin\Debug\XYZ.dll'
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at System.Reflection.AssemblyName.GetAssemblyName(String assemblyFile)
   at Codelyzer.Analysis.Build.ExternalReferenceLoader.LoadFromCompilation(HashSet`1 projectReferenceNames)

**Comment by mrkdeng** [comment]
Thank you for opening this issue! We've opened a ticket to track and investigate this issue internally.
